#!/bin/bash

is-running() {
  docker ps | grep -e "gitorious-$1[^/]" &>/dev/null
}

start() {
  echo -n "$1: "

  if is-running $1; then
    echo "already running"
  else
    if docker start gitorious-$1 &>/dev/null; then
      echo -e "\e[32mstarted\e[0m"
    else
      echo -e "\e[31mstart failed\e[0m (to get more details run: docker start gitorious-$1)"
    fi
  fi
}

stop() {
  echo -n "$1: "

  if is-running $1; then
    docker stop gitorious-$1 &>/dev/null && echo -e "\e[32mstopped\e[0m" || echo -e "\e[31mstop failed\e[0m"
  else
    echo "already stopped"
  fi
}

status() {
  echo -n "$1: "

  if is-running $1; then
    echo -e "\e[32mrunning\e[0m"
  else
    echo -e "\e[31mnot running\e[0m"
  fi
}

case "$1" in
  start)
    if [[ -n $2 ]]; then
      start $2
    else
      start mysql
      start redis
      start memcached
      start git-daemon
      start postfix
      start queue
      start sphinx
      start web
      start sshd
      start nginx
    fi
    ;;

  stop)
    if [[ -n $2 ]]; then
      stop $2
    else
      stop nginx
      stop sshd
      stop web
      stop sphinx
      stop queue
      stop postfix
      stop git-daemon
      stop memcached
      stop redis
      stop mysql
    fi
    ;;

  status)
    if [[ -n $2 ]]; then
      status $2
    else
      status mysql
      status redis
      status memcached
      status git-daemon
      status postfix
      status queue
      status sphinx
      status web
      status sshd
      status nginx
    fi
    ;;

  run)
    shift
    docker run --rm -t -i --link gitorious-mysql:mysql --link gitorious-redis:redis --link gitorious-memcached:memcached --link gitorious-sphinx:sphinx --link gitorious-postfix:smtp --volumes-from gitorious-data -v /var/log/gitorious/app:/srv/gitorious/app/log gitorious/app "$@"
    ;;

  rake)
    shift
    $0 run bin/rake "$@"
    ;;

  console)
    shift
    $0 run bin/console "$@"
    ;;

  *)
    echo "usage: gitoriousctl start|stop|status|run|rake|console"
    ;;
esac

exit 0
