#!/bin/sh

#!/bin/bash
if ! [ $(id -u) = 0 ]; then
   echo "You should run this script as root/superuser."
   exit 1
fi

echo "Starting the Gitorious installation..."

echo "Setting Gitorious hostname..."
./change_hostname.sh

echo "Disabling SELinux..."
sed -i "s/enforcing/disabled/" /etc/selinux/config
setenforce 0

echo "Installing Ruby 1.8.7, RubyGems 1.4.2 and Puppet..."
yum erase -y ruby rubygems
yum install -y ruby ruby-devel rubygems
gem update --system
gem update --system 1.4.2
gem install -y --no-ri --no-rdoc puppet -v=2.7.11

echo "Randomizing db password in puppet recipe..."
NEW_PASSWORD=$(date +%s | sha256sum | base64 | head -c 20) 
sed -i "s/DB_PASSWORD/$NEW_PASSWORD/" modules/gitorious/manifests/database.pp
sed -i "s/DB_PASSWORD/$NEW_PASSWORD/" modules/gitorious/files/config/database.yml
echo "Db password updated."

echo "Applying Puppet recipe (will take a while, be patient)..."
ruby apply_puppet_recipe.rb
PUPPETRESULT=$?
[ $PUPPETRESULT -ne 0 ] && echo "Installation failed." && exit
echo "Puppet recipe applied successfully."

echo "Creating the database..."
cd /var/www/gitorious/app && env RAILS_ENV=production bundle exec rake db:drop db:create db:migrate VERBOSE=false
echo "Database created."

echo "Randomizing cookie_secret..."
NEW_TOKEN=$(date +%s | sha256sum | base64 | head -c 40) 
sed -i "s/cookie_secret:.*/cookie_secret: $NEW_TOKEN/" /var/www/gitorious/app/config/gitorious.yml
echo "Rails cookie randomized."

# Anonymous pingback on install
curl -s http://getgitorious.com/installer_completed > /dev/null

echo "--------------------"
echo "Your installation of Gitorious Community Edition is complete."
echo "This installer is created and supported by Gitorious AS."
echo "For professional, long-term support, please consider Gitorious Enterprise Edition."
echo "http://gitorious.com"
echo "--------------------"



echo "Done. Please reboot the server."
